### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by TafadzwaMangena** [TafadzwaMangena/Agile_template_repo#4]
As a **role** I can **capability** so that **received benefit**

# Acceptance Criteria

* Acceptance Criteria1:
* Acceptance Criteria2:
* Acceptance Criteria3:
* Acceptance Criteria4:

# Tasks

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

**Comment by TafadzwaMangena** [comment]
In order to provide anonymous feedback as a user, I can choose to hide my identity in the poll response.

# Acceptance Criteria

- The option should be provided as a checkbox
- The checkbox should be “checked” by default
- The option should appear next to the submit button
- After submitting the default submission confirmation should be adjusted to include the user name.

# Tasks

- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submiter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality

**Comment by TafadzwaMangena** [comment]
## User Story:
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll

# Acceptance Criteria

- The poll should disappear at 11:59 PM on the target date.
- The real estate of the "Poll" should be reserved on the home page. a message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
- The administrator expiry date should be at least 3 days after the current date.

# Tasks

- [ ] Update the admin module view: the poll design (HTML and CSS) to include the date picker
- [ ] Update the website view: show "Stay Tuned" a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
